export type CatalogOption = { id: string; label: string; keywords?: string };

/** ISO 3166-1 alpha-2 countries (common set for account country). */
export const COUNTRIES: CatalogOption[] = [
  { id: 'AF', label: 'Afghanistan' },
  { id: 'AL', label: 'Albania' },
  { id: 'DZ', label: 'Algeria' },
  { id: 'AR', label: 'Argentina' },
  { id: 'AM', label: 'Armenia' },
  { id: 'AU', label: 'Australia' },
  { id: 'AT', label: 'Austria' },
  { id: 'AZ', label: 'Azerbaijan' },
  { id: 'BH', label: 'Bahrain' },
  { id: 'BD', label: 'Bangladesh' },
  { id: 'BY', label: 'Belarus' },
  { id: 'BE', label: 'Belgium' },
  { id: 'BJ', label: 'Benin' },
  { id: 'BO', label: 'Bolivia' },
  { id: 'BA', label: 'Bosnia and Herzegovina' },
  { id: 'BW', label: 'Botswana' },
  { id: 'BR', label: 'Brazil' },
  { id: 'BG', label: 'Bulgaria' },
  { id: 'BF', label: 'Burkina Faso' },
  { id: 'BI', label: 'Burundi' },
  { id: 'KH', label: 'Cambodia' },
  { id: 'CM', label: 'Cameroon' },
  { id: 'CA', label: 'Canada' },
  { id: 'TD', label: 'Chad' },
  { id: 'CL', label: 'Chile' },
  { id: 'CN', label: 'China' },
  { id: 'CO', label: 'Colombia' },
  { id: 'CG', label: 'Congo' },
  { id: 'CD', label: 'Congo (DRC)' },
  { id: 'CR', label: 'Costa Rica' },
  { id: 'CI', label: "Côte d'Ivoire" },
  { id: 'HR', label: 'Croatia' },
  { id: 'CU', label: 'Cuba' },
  { id: 'CY', label: 'Cyprus' },
  { id: 'CZ', label: 'Czechia' },
  { id: 'DK', label: 'Denmark' },
  { id: 'DJ', label: 'Djibouti' },
  { id: 'DO', label: 'Dominican Republic' },
  { id: 'EC', label: 'Ecuador' },
  { id: 'EG', label: 'Egypt' },
  { id: 'SV', label: 'El Salvador' },
  { id: 'ER', label: 'Eritrea' },
  { id: 'EE', label: 'Estonia' },
  { id: 'SZ', label: 'Eswatini' },
  { id: 'ET', label: 'Ethiopia' },
  { id: 'FI', label: 'Finland' },
  { id: 'FR', label: 'France' },
  { id: 'GA', label: 'Gabon' },
  { id: 'GM', label: 'Gambia' },
  { id: 'GE', label: 'Georgia' },
  { id: 'DE', label: 'Germany' },
  { id: 'GH', label: 'Ghana' },
  { id: 'GR', label: 'Greece' },
  { id: 'GT', label: 'Guatemala' },
  { id: 'GN', label: 'Guinea' },
  { id: 'HK', label: 'Hong Kong' },
  { id: 'HU', label: 'Hungary' },
  { id: 'IS', label: 'Iceland' },
  { id: 'IN', label: 'India' },
  { id: 'ID', label: 'Indonesia' },
  { id: 'IR', label: 'Iran' },
  { id: 'IQ', label: 'Iraq' },
  { id: 'IE', label: 'Ireland' },
  { id: 'IL', label: 'Israel' },
  { id: 'IT', label: 'Italy' },
  { id: 'JM', label: 'Jamaica' },
  { id: 'JP', label: 'Japan' },
  { id: 'JO', label: 'Jordan' },
  { id: 'KZ', label: 'Kazakhstan' },
  { id: 'KE', label: 'Kenya' },
  { id: 'KW', label: 'Kuwait' },
  { id: 'KG', label: 'Kyrgyzstan' },
  { id: 'LA', label: 'Laos' },
  { id: 'LV', label: 'Latvia' },
  { id: 'LB', label: 'Lebanon' },
  { id: 'LR', label: 'Liberia' },
  { id: 'LY', label: 'Libya' },
  { id: 'LT', label: 'Lithuania' },
  { id: 'LU', label: 'Luxembourg' },
  { id: 'MG', label: 'Madagascar' },
  { id: 'MW', label: 'Malawi' },
  { id: 'MY', label: 'Malaysia' },
  { id: 'ML', label: 'Mali' },
  { id: 'MT', label: 'Malta' },
  { id: 'MR', label: 'Mauritania' },
  { id: 'MU', label: 'Mauritius' },
  { id: 'MX', label: 'Mexico' },
  { id: 'MD', label: 'Moldova' },
  { id: 'MN', label: 'Mongolia' },
  { id: 'MA', label: 'Morocco' },
  { id: 'MZ', label: 'Mozambique' },
  { id: 'MM', label: 'Myanmar' },
  { id: 'NA', label: 'Namibia' },
  { id: 'NP', label: 'Nepal' },
  { id: 'NL', label: 'Netherlands' },
  { id: 'NZ', label: 'New Zealand' },
  { id: 'NI', label: 'Nicaragua' },
  { id: 'NE', label: 'Niger' },
  { id: 'NG', label: 'Nigeria' },
  { id: 'MK', label: 'North Macedonia' },
  { id: 'NO', label: 'Norway' },
  { id: 'OM', label: 'Oman' },
  { id: 'PK', label: 'Pakistan' },
  { id: 'PS', label: 'Palestine' },
  { id: 'PA', label: 'Panama' },
  { id: 'PY', label: 'Paraguay' },
  { id: 'PE', label: 'Peru' },
  { id: 'PH', label: 'Philippines' },
  { id: 'PL', label: 'Poland' },
  { id: 'PT', label: 'Portugal' },
  { id: 'QA', label: 'Qatar' },
  { id: 'RO', label: 'Romania' },
  { id: 'RU', label: 'Russia' },
  { id: 'RW', label: 'Rwanda' },
  { id: 'SA', label: 'Saudi Arabia' },
  { id: 'SN', label: 'Senegal' },
  { id: 'RS', label: 'Serbia' },
  { id: 'SL', label: 'Sierra Leone' },
  { id: 'SG', label: 'Singapore' },
  { id: 'SK', label: 'Slovakia' },
  { id: 'SI', label: 'Slovenia' },
  { id: 'SO', label: 'Somalia' },
  { id: 'ZA', label: 'South Africa' },
  { id: 'KR', label: 'South Korea' },
  { id: 'SS', label: 'South Sudan' },
  { id: 'ES', label: 'Spain' },
  { id: 'LK', label: 'Sri Lanka' },
  { id: 'SD', label: 'Sudan' },
  { id: 'SE', label: 'Sweden' },
  { id: 'CH', label: 'Switzerland' },
  { id: 'SY', label: 'Syria' },
  { id: 'TW', label: 'Taiwan' },
  { id: 'TJ', label: 'Tajikistan' },
  { id: 'TZ', label: 'Tanzania' },
  { id: 'TH', label: 'Thailand' },
  { id: 'TG', label: 'Togo' },
  { id: 'TN', label: 'Tunisia' },
  { id: 'TR', label: 'Turkey' },
  { id: 'TM', label: 'Turkmenistan' },
  { id: 'UG', label: 'Uganda' },
  { id: 'UA', label: 'Ukraine' },
  { id: 'AE', label: 'United Arab Emirates' },
  { id: 'GB', label: 'United Kingdom' },
  { id: 'US', label: 'United States' },
  { id: 'UY', label: 'Uruguay' },
  { id: 'UZ', label: 'Uzbekistan' },
  { id: 'VE', label: 'Venezuela' },
  { id: 'VN', label: 'Vietnam' },
  { id: 'YE', label: 'Yemen' },
  { id: 'ZM', label: 'Zambia' },
  { id: 'ZW', label: 'Zimbabwe' },
].map((c) => ({ ...c, keywords: `${c.id} ${c.label}`.toLowerCase() }));

/** ISO 4217 currencies commonly used for peer lending. */
export const CURRENCIES: CatalogOption[] = [
  { id: 'AED', label: 'UAE Dirham' },
  { id: 'AFN', label: 'Afghan Afghani' },
  { id: 'ALL', label: 'Albanian Lek' },
  { id: 'AMD', label: 'Armenian Dram' },
  { id: 'ARS', label: 'Argentine Peso' },
  { id: 'AUD', label: 'Australian Dollar' },
  { id: 'AZN', label: 'Azerbaijani Manat' },
  { id: 'BDT', label: 'Bangladeshi Taka' },
  { id: 'BGN', label: 'Bulgarian Lev' },
  { id: 'BHD', label: 'Bahraini Dinar' },
  { id: 'BRL', label: 'Brazilian Real' },
  { id: 'CAD', label: 'Canadian Dollar' },
  { id: 'CHF', label: 'Swiss Franc' },
  { id: 'CLP', label: 'Chilean Peso' },
  { id: 'CNY', label: 'Chinese Yuan' },
  { id: 'COP', label: 'Colombian Peso' },
  { id: 'CZK', label: 'Czech Koruna' },
  { id: 'DKK', label: 'Danish Krone' },
  { id: 'DJF', label: 'Djiboutian Franc' },
  { id: 'EGP', label: 'Egyptian Pound' },
  { id: 'ERN', label: 'Eritrean Nakfa' },
  { id: 'ETB', label: 'Ethiopian Birr' },
  { id: 'EUR', label: 'Euro' },
  { id: 'GBP', label: 'British Pound' },
  { id: 'GHS', label: 'Ghanaian Cedi' },
  { id: 'HKD', label: 'Hong Kong Dollar' },
  { id: 'HUF', label: 'Hungarian Forint' },
  { id: 'IDR', label: 'Indonesian Rupiah' },
  { id: 'ILS', label: 'Israeli Shekel' },
  { id: 'INR', label: 'Indian Rupee' },
  { id: 'IQD', label: 'Iraqi Dinar' },
  { id: 'IRR', label: 'Iranian Rial' },
  { id: 'JPY', label: 'Japanese Yen' },
  { id: 'KES', label: 'Kenyan Shilling' },
  { id: 'KRW', label: 'South Korean Won' },
  { id: 'KWD', label: 'Kuwaiti Dinar' },
  { id: 'LBP', label: 'Lebanese Pound' },
  { id: 'LKR', label: 'Sri Lankan Rupee' },
  { id: 'MAD', label: 'Moroccan Dirham' },
  { id: 'MMK', label: 'Myanmar Kyat' },
  { id: 'MXN', label: 'Mexican Peso' },
  { id: 'MYR', label: 'Malaysian Ringgit' },
  { id: 'NGN', label: 'Nigerian Naira' },
  { id: 'NOK', label: 'Norwegian Krone' },
  { id: 'NPR', label: 'Nepalese Rupee' },
  { id: 'NZD', label: 'New Zealand Dollar' },
  { id: 'OMR', label: 'Omani Rial' },
  { id: 'PHP', label: 'Philippine Peso' },
  { id: 'PKR', label: 'Pakistani Rupee' },
  { id: 'PLN', label: 'Polish Zloty' },
  { id: 'QAR', label: 'Qatari Riyal' },
  { id: 'RON', label: 'Romanian Leu' },
  { id: 'RUB', label: 'Russian Ruble' },
  { id: 'RWF', label: 'Rwandan Franc' },
  { id: 'SAR', label: 'Saudi Riyal' },
  { id: 'SEK', label: 'Swedish Krona' },
  { id: 'SGD', label: 'Singapore Dollar' },
  { id: 'SOS', label: 'Somali Shilling' },
  { id: 'SSP', label: 'South Sudanese Pound' },
  { id: 'THB', label: 'Thai Baht' },
  { id: 'TRY', label: 'Turkish Lira' },
  { id: 'TWD', label: 'New Taiwan Dollar' },
  { id: 'TZS', label: 'Tanzanian Shilling' },
  { id: 'UAH', label: 'Ukrainian Hryvnia' },
  { id: 'UGX', label: 'Ugandan Shilling' },
  { id: 'USD', label: 'US Dollar' },
  { id: 'UYU', label: 'Uruguayan Peso' },
  { id: 'UZS', label: 'Uzbekistani Som' },
  { id: 'VND', label: 'Vietnamese Dong' },
  { id: 'XAF', label: 'Central African CFA Franc' },
  { id: 'XOF', label: 'West African CFA Franc' },
  { id: 'ZAR', label: 'South African Rand' },
  { id: 'ZMW', label: 'Zambian Kwacha' },
].map((c) => ({ ...c, keywords: `${c.id} ${c.label}`.toLowerCase() }));

export function filterCatalog(options: CatalogOption[], query: string): CatalogOption[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return options;
  }
  return options.filter((o) => (o.keywords ?? `${o.id} ${o.label}`.toLowerCase()).includes(q));
}

export function catalogLabel(options: CatalogOption[], id: string | null | undefined): string {
  if (!id) {
    return '';
  }
  const hit = options.find((o) => o.id === id);
  return hit ? `${hit.id} · ${hit.label}` : id;
}
