import type { CatalogOption } from './catalogs';

export const INSTITUTION_TYPES: CatalogOption[] = [
  { id: 'bank', label: 'Bank' },
  { id: 'sacco', label: 'SACCO / Credit union' },
  { id: 'microfinance', label: 'Microfinance' },
  { id: 'person', label: 'Person' },
  { id: 'hedge_fund', label: 'Hedge fund' },
  { id: 'private_equity', label: 'Private equity' },
  { id: 'fintech', label: 'Fintech / digital lender' },
  { id: 'insurance', label: 'Insurance' },
  { id: 'government', label: 'Government / public lender' },
  { id: 'employer', label: 'Employer' },
  { id: 'other', label: 'Other' },
].map((o) => ({ ...o, keywords: `${o.id} ${o.label}`.toLowerCase() }));

const OTHER: CatalogOption = { id: 'other', label: 'Other', keywords: 'other custom' };

function opts(names: string[]): CatalogOption[] {
  const seen = new Set<string>();
  const list: CatalogOption[] = [];
  for (const label of names) {
    const id = label
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_|_$/g, '');
    if (!id || seen.has(id)) continue;
    seen.add(id);
    list.push({ id, label, keywords: label.toLowerCase() });
  }
  list.push({ ...OTHER });
  return list;
}

/**
 * Global searchable catalogs (not country-specific).
 * Lists major institutions worldwide; use Other for anything missing.
 */
export const INSTITUTIONS_BY_TYPE: Record<string, CatalogOption[]> = {
  bank: opts([
    // Global / multi-region
    'HSBC',
    'Citibank',
    'Citi',
    'Standard Chartered',
    'Deutsche Bank',
    'BNP Paribas',
    'Société Générale',
    'Barclays',
    'UBS',
    'Credit Suisse',
    'ING',
    'Santander',
    'BBVA',
    'UniCredit',
    'Intesa Sanpaolo',
    'Crédit Agricole',
    'Rabobank',
    'Nordea',
    'Danske Bank',
    'SEB',
    'Swedbank',
    'Commerzbank',
    'DZ Bank',
    'Raiffeisen Bank International',
    'Erste Group',
    'KBC Bank',
    'ABN AMRO',
    'Lloyds Bank',
    'NatWest',
    'HSBC UK',
    'Bank of Scotland',
    'Nationwide Building Society',
    // North America
    'JPMorgan Chase',
    'Bank of America',
    'Wells Fargo',
    'Goldman Sachs',
    'Morgan Stanley',
    'U.S. Bank',
    'PNC Bank',
    'Truist',
    'Capital One',
    'TD Bank',
    'TD Canada Trust',
    'Royal Bank of Canada',
    'RBC',
    'Scotiabank',
    'BMO',
    'CIBC',
    'National Bank of Canada',
    'Ally Bank',
    'Charles Schwab Bank',
    'American Express National Bank',
    'Discover Bank',
    'Citizens Bank',
    'Fifth Third Bank',
    'KeyBank',
    'Regions Bank',
    'Huntington Bank',
    'M&T Bank',
    'Bank of New York Mellon',
    'State Street',
    // Latin America
    'Itaú Unibanco',
    'Banco Bradesco',
    'Banco do Brasil',
    'Banco Santander Brasil',
    'Banorte',
    'BBVA México',
    'Banamex',
    'Banco de Chile',
    'Banco Estado',
    'Bancolombia',
    'Banco de Bogotá',
    'Banco Galicia',
    'Banco Nación',
    'BCP',
    'Interbank',
    // Middle East & Africa
    'Commercial Bank of Ethiopia',
    'Awash Bank',
    'Dashen Bank',
    'Bank of Abyssinia',
    'Cooperative Bank of Oromia',
    'Nib International Bank',
    'Hibret Bank',
    'Wegagen Bank',
    'Zemen Bank',
    'Bunna Bank',
    'Abay Bank',
    'Enat Bank',
    'Amhara Bank',
    'Equity Bank',
    'KCB Bank',
    'Absa',
    'Absa Bank',
    'Standard Bank',
    'FirstRand',
    'Nedbank',
    'Capitec',
    'FNB',
    'Ecobank',
    'Access Bank',
    'Zenith Bank',
    'GTBank',
    'UBA',
    'First Bank of Nigeria',
    'NCBA',
    'Co-operative Bank of Kenya',
    'Bank of Africa',
    'Attijariwafa Bank',
    'Banque Centrale Populaire',
    'QNB',
    'Emirates NBD',
    'First Abu Dhabi Bank',
    'ADCB',
    'Mashreq',
    'National Bank of Kuwait',
    'Kuwait Finance House',
    'Al Rajhi Bank',
    'Saudi National Bank',
    'Riyad Bank',
    'BankMuscat',
    'Bank of Palestine',
    'Banque Misr',
    'National Bank of Egypt',
    'CIB Egypt',
    // Asia-Pacific
    'Industrial and Commercial Bank of China',
    'ICBC',
    'China Construction Bank',
    'Agricultural Bank of China',
    'Bank of China',
    'Bank of Communications',
    'China Merchants Bank',
    'Ping An Bank',
    'Mitsubishi UFJ',
    'MUFG',
    'Sumitomo Mitsui',
    'SMBC',
    'Mizuho',
    'Japan Post Bank',
    'State Bank of India',
    'HDFC Bank',
    'ICICI Bank',
    'Axis Bank',
    'Kotak Mahindra Bank',
    'Punjab National Bank',
    'Bank of Baroda',
    'Canara Bank',
    'DBS Bank',
    'OCBC',
    'UOB',
    'Maybank',
    'CIMB',
    'Public Bank Berhad',
    'Bangkok Bank',
    'Kasikornbank',
    'Siam Commercial Bank',
    'Krungthai Bank',
    'Bank Central Asia',
    'Bank Mandiri',
    'Bank Rakyat Indonesia',
    'BDO Unibank',
    'Metrobank',
    'BPI',
    'Commonwealth Bank of Australia',
    'Westpac',
    'ANZ',
    'NAB',
    'ASB Bank',
    'Kiwibank',
    'Shinhan Bank',
    'KB Kookmin Bank',
    'Hana Bank',
    'Woori Bank',
    'Woori',
    'KB Bank',
    'Bank of Taiwan',
    'Cathay United Bank',
    'CTBC Bank',
    'Hang Seng Bank',
    'Bank of East Asia',
    'Mashreq Bank',
    'Habib Bank',
    'HBL',
    'Meezan Bank',
    'Bank Alfalah',
    'BRAC Bank',
    'Dutch-Bangla Bank',
    'Islami Bank Bangladesh',
    // Europe (more)
    'CaixaBank',
    'Sberbank',
    'VTB',
    'Alfa-Bank',
    'PKO Bank Polski',
    'mBank',
    'OTP Bank',
    'Banca Transilvania',
    'Bank of Ireland',
    'AIB',
    'DNB',
    'Handelsbanken',
    'Revolut',
    'N26',
    'Monzo',
    'Starling Bank',
    // Central & Eastern Europe / Caucasus / Central Asia
    'Raiffeisen Bank',
    'Bank Pekao',
    'ING Bank Śląski',
    'Česká spořitelna',
    'Komerční banka',
    'ČSOB',
    'SLSP',
    'Tatra Banka',
    'OTP Bank Ukraine',
    'PrivatBank',
    'Bank of Georgia',
    'TBC Bank',
    'Ameriabank',
    'Halyk Bank',
    'Kaspi Bank',
    'Kapitalbank',
    'Ipoteka Bank',
    'Agrobank Uzbekistan',
    // Southeast Asia & South Asia (more)
    'Vietcombank',
    'VietinBank',
    'BIDV',
    'Techcombank',
    'VPBank',
    'Sacombank',
    'MB Bank',
    'TPBank',
    'ACB',
    'Bank Islam Malaysia',
    'RHB Bank',
    'Hong Leong Bank',
    'AmBank',
    'Bank Rakyat',
    'Bank Negara Indonesia',
    'Bank Negara Indonesia (BNI)',
    'Permata Bank',
    'CIMB Niaga',
    'Danamon',
    'Bank Mega',
    'Security Bank',
    'UnionBank Philippines',
    'Land Bank of the Philippines',
    'RCBC',
    'China Bank',
    'Bank of the Philippine Islands',
    'Sampath Bank',
    'Commercial Bank of Ceylon',
    'Hatton National Bank',
    'People\'s Bank Sri Lanka',
    'Bank of Maldives',
    'Nabil Bank',
    'Nepal Investment Mega Bank',
    'Rastriya Banijya Bank',
    'Bank Asia',
    'Eastern Bank Limited',
    'City Bank Bangladesh',
    'Standard Chartered Pakistan',
    'United Bank Limited',
    'Allied Bank',
    'MCB Bank',
    'Askari Bank',
    'BankIslami',
    'Yes Bank',
    'IndusInd Bank',
    'IDFC First Bank',
    'Federal Bank',
    'South Indian Bank',
    'Bandhan Bank India',
    'AU Small Finance Bank',
    // Africa (broader)
    'Commercial International Bank',
    'Banque du Caire',
    'Housing and Development Bank',
    'Bank of Khartoum',
    'Omdurman National Bank',
    'CRDB Bank',
    'NMB Bank Tanzania',
    'Stanbic Bank',
    'Stanbic IBTC',
    'Diamond Bank',
    'Fidelity Bank Nigeria',
    'Union Bank of Nigeria',
    'Wema Bank',
    'Sterling Bank',
    'Polari Bank',
    'CalBank',
    'GCB Bank',
    'Ecobank Ghana',
    'Absa Ghana',
    'Société Générale Ghana',
    'Bank of Accra',
    'Banque Atlantique',
    'Orabank',
    'BGFIBank',
    'Ecobank Côte d\'Ivoire',
    'Banque de Kigali',
    'Equity Bank Rwanda',
    'Bank of Kigali',
    'I&M Bank',
    'DFCU Bank',
    'Centenary Bank',
    'Stanbic Bank Uganda',
    'Absa Uganda',
    'National Bank of Malawi',
    'FDH Bank',
    'Standard Bank Malawi',
    'Zanaco',
    'Atlas Mara',
    'BancABC',
    'CBZ Bank',
    'Steward Bank',
    'NMB Bank Zimbabwe',
    'BancABC Botswana',
    'First National Bank Botswana',
    'Standard Bank Namibia',
    'Bank Windhoek',
    'Nedbank Namibia',
    'First National Bank Namibia',
    'Bank of Botswana',
    'Mauritius Commercial Bank',
    'SBM Bank',
    'Absa Bank Mauritius',
    'Bank of Mauritius',
    'BMCE Bank of Africa',
    'Bank of Africa Senegal',
    'Ecobank Senegal',
    'Banque Internationale pour le Commerce et l\'Industrie',
    'Commercial Bank of Dubai',
    'Dubai Islamic Bank',
    'Abu Dhabi Islamic Bank',
    'Ajman Bank',
    'RAKBANK',
    'Banque Saudi Fransi',
    'Banque Saudi Fransi (BSF)',
    'Arab National Bank',
    'Banque du Liban et d\'Outre-Mer',
    'BLOM Bank',
    'Byblos Bank',
    'Bank Audi',
    'Arab Bank',
    'Cairo Amman Bank',
    'Housing Bank for Trade and Finance',
    'Bank of Jordan',
    'Jordan Islamic Bank',
    'Qatar Islamic Bank',
    'Doha Bank',
    'Commercial Bank of Qatar',
    'Ahli United Bank',
    'Bank of Bahrain and Kuwait',
    'National Bank of Bahrain',
    'Bank Dhofar',
    'Sohar International',
    'National Bank of Oman',
    // Americas (more)
    'Scotiabank México',
    'HSBC México',
    'Santander México',
    'Banco Azteca',
    'Inbursa',
    'Banco Popular Dominicano',
    'Banreservas',
    'Banco de Crédito del Perú',
    'BBVA Perú',
    'Scotiabank Perú',
    'Banco Guayaquil',
    'Banco Pichincha',
    'Produbanco',
    'Banco de Occidente',
    'Davivienda',
    'Banco Popular Colombia',
    'Banco Estado Chile',
    'Scotiabank Chile',
    'Banco de Crédito e Inversiones',
    'BCI',
    'Itaú Chile',
    'Banco Macro',
    'Banco Supervielle',
    'Banco Patagonia',
    'BBVA Argentina',
    'Santander Río',
    'Caixa Econômica Federal',
    'Safra',
    'BTG Pactual',
    'Nubank Conta',
    'Banco Original',
    'Inter',
    'C6 Bank',
    'Banrisul',
    'Sicoob',
    'Sicredi',
    'Banco Popular de Puerto Rico',
    'Oriental Bank',
    'FirstBank Puerto Rico',
    'Scotiabank Caribbean',
    'Republic Bank',
    'FirstCaribbean International Bank',
    'RBC Royal Bank Caribbean',
    // East Asia (more)
    'Postal Savings Bank of China',
    'China Minsheng Bank',
    'China CITIC Bank',
    'Shanghai Pudong Development Bank',
    'Industrial Bank China',
    'Hua Xia Bank',
    'Bank of Beijing',
    'Bank of Shanghai',
    'DBS Hong Kong',
    'Standard Chartered Hong Kong',
    'HSBC Hong Kong',
    'Bank of China Hong Kong',
    'Chong Hing Bank',
    'Dah Sing Bank',
    'Shanghai Commercial Bank',
    'E.Sun Bank',
    'Taishin Bank',
    'Mega International Commercial Bank',
    'First Commercial Bank Taiwan',
    'Hua Nan Bank',
    'Chang Hwa Bank',
    'Resona Bank',
    'Shinsei Bank',
    'Rakuten Bank',
    'Sony Bank',
    'Seven Bank',
    'SBI Sumishin Net Bank',
    'NH Bank',
    'Industrial Bank of Korea',
    'Busan Bank',
    'Daegu Bank',
    'Jeonbuk Bank',
    'Kakao Bank',
    'K Bank',
    'Toss Bank Korea',
    'Macquarie Bank',
    'Bendigo Bank',
    'Bank of Queensland',
    'Suncorp Bank',
    'ING Australia',
    'ME Bank',
    'Bank of New Zealand',
    'TSB Bank New Zealand',
    'Heartland Bank',
    // Development / multilateral / islamic majors often used as lenders
    'Islamic Development Bank',
    'European Bank for Reconstruction and Development',
    'Inter-American Development Bank',
    'New Development Bank',
    'Asian Infrastructure Investment Bank',
    // Additional global banks
    'Bank of Valletta',
    'APS Bank',
    'Banco BPI',
    'Novo Banco',
    'Millennium BCP',
    'Caixa Geral de Depósitos',
    'Banca Monte dei Paschi',
    'BPER Banca',
    'Mediobanca',
    'Credit Mutuel',
    'La Banque Postale',
    'BPCE',
    'Landesbank Baden-Württemberg',
    'Bayerische Landesbank',
    'Helaba',
    'NORD/LB',
    'Postbank',
    'Sparkasse',
    'Volksbank',
    'Bank Pekao SA',
    'Alior Bank',
    'Getin Noble Bank',
    'Raiffeisenbank Czech Republic',
    'UniCredit Bank Czech Republic and Slovakia',
    'Erste Bank Hungary',
    'OTP Bank Romania',
    'Banca Comercială Română',
    'Garanti BBVA',
    'İş Bankası',
    'Akbank',
    'Yapı Kredi',
    'Ziraat Bankası',
    'Halkbank',
    'VakıfBank',
    'Bank Hapoalim',
    'Bank Leumi',
    'Mizrahi-Tefahot',
    'First International Bank of Israel',
    'Bank of Cyprus',
    'Hellenic Bank',
    'Alpha Bank',
    'Eurobank',
    'National Bank of Greece',
    'Piraeus Bank',
    'Banco Sabadell',
    'Bankinter',
    'Abanca',
    'Kutxabank',
    'Unicaja Banco',
    'ING España',
    'Openbank Spain',
    'SpareBank 1',
    'DNB Bank ASA',
    'Nordea Bank Abp',
    'OP Financial Group',
    'Aktia Bank',
    'S-Bank',
    'Länsförsäkringar Bank',
    'SBAB',
    'Ikano Bank',
    'Jyske Bank',
    'Sydbank',
    'Spar Nord',
    'Arbejdernes Landsbank',
    'Banco BIC',
    'Banco Angolano de Investimentos',
    'Standard Bank Angola',
    'Ecobank Nigeria',
    'Keystone Bank',
    'Heritage Bank Nigeria',
    'Providus Bank',
    'Titan Trust Bank',
    'Globus Bank',
    'PremiumTrust Bank',
    'SunTrust Bank Nigeria',
    'Bank of Industry Nigeria',
    'Development Bank of Nigeria',
    'National Bank of Ethiopia',
    'Lion International Bank',
    'Gadaa Bank',
    'Siinqee Bank',
    'Tsedey Bank',
    'Hijra Bank',
    'ZamZam Bank',
    'Shabelle Bank',
    'Ahadu Bank',
    'Goh Betoch Bank',
    'Bank of South Sudan',
    'Ivory Bank',
    'Cooperative Bank of South Sudan',
  ]),
  sacco: opts([
    'Navy Federal Credit Union',
    'State Employees Credit Union',
    'Pentagon Federal Credit Union',
    'Alliant Credit Union',
    'BECU',
    'SchoolsFirst Federal Credit Union',
    'Golden 1 Credit Union',
    'America First Credit Union',
    'Vystar Credit Union',
    'Suncoast Credit Union',
    'UN SACCO',
    'Mwalimu National SACCO',
    'Stima SACCO',
    'Harambee SACCO',
    'Kenya Police SACCO',
    'Afya SACCO',
    'Tower SACCO',
    'Waumini SACCO',
    'Hazina SACCO',
    'Ukulima SACCO',
    'Addis Savings & Credit',
    'Oromia SACCO',
    'Amhara Credit & Savings Institution',
    'Dedebit Credit & Savings',
    'Desjardins',
    'Vancity',
    'Coast Capital Savings',
    'Servus Credit Union',
    'Meridian Credit Union',
    'Local credit union',
    'Workplace credit union',
    'Community SACCO',
  ]),
  microfinance: opts([
    'Grameen Bank',
    'BRAC',
    'ASA Bangladesh',
    'Bandhan Bank',
    'SKS Microfinance',
    'Bharat Financial Inclusion',
    'Compartamos Banco',
    'BancoSol',
    'MiBanco',
    'VisionFund',
    'Opportunity International',
    'FINCA',
    'Accion',
    'Kiva partner lender',
    'ACSI',
    'DECSI',
    'Omo Microfinance',
    'PEACE MFI',
    'Metemamen Microfinance',
    'Wasasa Microfinance',
    'Faulu Kenya',
    'KWFT',
    'Musoni',
    'SMEPedia',
    'LAPO Microfinance',
    'ACCION Nigeria',
    'ASA Philippines',
    'CARD MRI',
    'TSPI',
    'Community microfinance',
  ]),
  person: opts([
    'Family member',
    'Friend',
    'Colleague',
    'Business partner',
    'Private individual',
    'Informal lender',
  ]),
  hedge_fund: opts([
    'Bridgewater Associates',
    'Citadel',
    'Renaissance Technologies',
    'Two Sigma',
    'AQR Capital Management',
    'Millennium Management',
    'Elliott Management',
    'DE Shaw',
    'Point72',
    'Tiger Global',
    'Coatue',
    'Viking Global',
    'Baupost Group',
    'Appaloosa Management',
    'Pershing Square',
    'Third Point',
    'Man Group',
    'Winton Group',
    'Marshall Wace',
    'Local / regional fund',
  ]),
  private_equity: opts([
    'Blackstone',
    'KKR',
    'Carlyle Group',
    'Apollo Global Management',
    'TPG',
    'Warburg Pincus',
    'Bain Capital',
    'Advent International',
    'CVC Capital Partners',
    'EQT',
    'Permira',
    'Lone Star Funds',
    'Cerberus Capital',
    'Ares Management',
    'Local PE firm',
  ]),
  fintech: opts([
    'Affirm',
    'Klarna',
    'Afterpay',
    'Zip',
    'Sezzle',
    'PayPal Credit',
    'SoFi',
    'LendingClub',
    'Prosper',
    'Upstart',
    'Avant',
    'Upgrade',
    'Figure',
    'Rocket Mortgage',
    'Better Mortgage',
    'LoanDepot',
    'Marcus by Goldman Sachs',
    'Apple Card / Goldman Sachs',
    'Branch',
    'Tala',
    'Carbon',
    'FairMoney',
    'PalmPay',
    'Opay',
    'M-Pesa Fuliza',
    'M-Shwari',
    'KCB M-Pesa',
    'Telebirr Credit',
    'CBE Birr',
    'Kifiya',
    'Chipper Cash',
    'Flutterwave Capital',
    'Paystack Lending',
    'GCash',
    'Maya',
    'Grab Financial',
    'SeaMoney',
    'Ant Group',
    'WeBank',
    'KakaoBank',
    'Toss Bank',
    'Nubank',
    'Mercado Pago',
    'Ualá',
    'Revolut',
    'N26',
    'Wise',
    'Cash App Borrow',
    'Chime Credit Builder',
    'Varo',
    'Current',
    'Dave',
    'Earnin',
    'Brigit',
    'MoneyLion',
    'Creditas',
    'Cora',
    'Neon Brasil',
    'PicPay',
    'PagBank',
    'Openbank',
    'Bunq',
    'Trade Republic',
    'Scalable Capital',
    'Tide',
    'Starling Business',
    'Curve',
    'Yolt',
    'Atom Bank',
    'Chase UK',
    'Virgin Money',
    'First Direct',
    'Monese',
    'Pockit',
    'Lyudi',
    'Tinkoff',
    'Yandex Pay',
    'SberPay',
    'Paytm',
    'PhonePe',
    'Google Pay India',
    'Razorpay Capital',
    'KreditBee',
    'LazyPay',
    'Simpl',
    'CASHe',
    'EarlySalary',
    'Navi',
    'Groww Credit',
    'JULO',
    'Akulaku',
    'Kredivo',
    'Home Credit',
    'AEON Credit',
    'Shopee PayLater',
    'Lazada Credit',
    'Tonik',
    'UNOBank',
    'CIMB Philippines',
    'Mynt',
    'Boost',
    'Touch \'n Go',
    'BigPay',
    'AlipayHK',
    'WeChat Pay HK',
    'PayPay',
    'LINE Pay',
    'Merpay',
    'au PAY',
    'd払い',
    'Rakuten Card',
    'Samsung Money',
    'Naver Pay',
    'Toss',
    'Bank of the Future',
    'TymeBank',
    'Discovery Bank',
    'Bank Zero',
    'Yoco Capital',
    'Lulalend',
    'Retail Capital',
    'Float',
    'Jumo',
    'Mkopo Rahisi',
    'Pezesha',
    'Lulalend Kenya',
    'Aella Credit',
    'Renmoney',
    'Lidya',
    'Kuda',
    'PiggyVest',
    'Cowrywise',
    'Mintyn',
    'Sparkle',
    'ALAT by Wema',
    'VBank',
    'Eyowo',
  ]),
  mobile_money: opts([
    'M-Pesa',
    'Airtel Money',
    'MTN MoMo',
    'Orange Money',
    'Telebirr',
    'CBE Birr',
    'Wave',
    'GCash',
    'Maya',
    'GrabPay',
    'GoPay',
    'Dana',
    'OVO',
    'ShopeePay',
    'Alipay',
    'WeChat Pay',
    'Paytm',
    'PhonePe',
    'Google Pay',
    'Apple Cash',
    'Cash App',
    'Venmo',
    'Zelle',
    'Pix',
    'Nequi',
    'Yape',
    'Mercado Pago',
    'Chipper Cash',
    'PalmPay',
    'Opay',
    'Local mobile money',
  ]),
  wallet: opts([
    'PayPal',
    'Wise',
    'Revolut',
    'Cash App',
    'Venmo',
    'Apple Wallet / Cash',
    'Google Wallet',
    'Samsung Wallet',
    'Alipay',
    'WeChat Pay',
    'Skrill',
    'Neteller',
    'Payoneer',
    'Stripe Balance',
    'Crypto self-custody',
    'Coinbase',
    'Binance',
    'Local e-wallet',
  ]),
  insurance: opts([
    'MetLife',
    'Prudential',
    'AIA',
    'Allianz',
    'AXA',
    'Zurich Insurance',
    'Manulife',
    'Sun Life',
    'New York Life',
    'Northwestern Mutual',
    'MassMutual',
    'Pacific Life',
    'Ethiopian Insurance Corporation',
    'Awash Insurance',
    'Nile Insurance',
    'Nyala Insurance',
    'Global Insurance',
    'Life / annuity lender',
    'Policy loan provider',
  ]),
  government: opts([
    'Federal student loan program',
    'National housing finance agency',
    'Development bank',
    'Export-import bank',
    'SME development fund',
    'Agricultural credit corporation',
    'Municipal lending program',
    'Development Bank of Ethiopia',
    'World Bank / IFC on-lending',
    'African Development Bank facility',
    'Asian Development Bank facility',
    'European Investment Bank facility',
    'Public mortgage agency',
    'Veterans / public housing loan',
  ]),
  employer: opts([
    'Employer salary advance',
    'Staff loan scheme',
    'Corporate treasury loan',
    'ESOP / share loan',
    'Relocation loan',
  ]),
  other: opts(['Custom lender', 'Unlisted institution']),
};

export function institutionsForType(typeId: string): CatalogOption[] {
  return INSTITUTIONS_BY_TYPE[typeId] ?? [{ ...OTHER }];
}

/** Map money-account types → institution catalog keys (global, not country-locked). */
export function institutionsForAccountType(accountType: string): CatalogOption[] {
  switch (accountType) {
    case 'bank':
      return institutionsForType('bank');
    case 'mobile_money':
      return institutionsForType('mobile_money');
    case 'wallet':
      return institutionsForType('wallet');
    case 'cash':
      return opts(['Cash on hand', 'Safe', 'Petty cash']);
    case 'other':
    default:
      return institutionsForType('other');
  }
}

export function resolveInstitutionLabel(
  typeId: string,
  institutionId: string,
  otherName: string,
): string {
  const other = otherName.trim();
  if (!institutionId || institutionId === 'other') {
    return other;
  }
  const hit = institutionsForType(typeId).find((o) => o.id === institutionId);
  if (!hit || hit.id === 'other') {
    return other;
  }
  return hit.label;
}

export function resolveAccountInstitutionLabel(
  accountType: string,
  institutionId: string,
  otherName: string,
): string {
  const other = otherName.trim();
  if (!institutionId || institutionId === 'other') {
    return other || (accountType === 'cash' ? 'Cash' : '');
  }
  const hit = institutionsForAccountType(accountType).find((o) => o.id === institutionId);
  if (!hit || hit.id === 'other') {
    return other;
  }
  return hit.label;
}
