// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID                  uuid.UUID  `json:"id"`
	Email               string     `json:"email"`
	PhoneE164           *string    `json:"phone_e164"`
	Username            *string    `json:"username"`
	DisplayName         string     `json:"display_name"`
	AvatarObjectKey     *string    `json:"avatar_object_key"`
	Timezone            string     `json:"timezone"`
	Locale              string     `json:"locale"`
	DefaultCurrencyCode *string    `json:"default_currency_code"`
	PasswordHash        string     `json:"password_hash"`
	EmailVerifiedAt     *time.Time `json:"email_verified_at"`
	Status              string     `json:"status"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           *time.Time `json:"deleted_at"`
}

type UserSession struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	DeviceLabel      *string    `json:"device_label"`
	CreatedAt        time.Time  `json:"created_at"`
	LastUsedAt       time.Time  `json:"last_used_at"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
}

type VerificationChallenge struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Channel     string     `json:"channel"`
	Destination string     `json:"destination"`
	CodeHash    string     `json:"code_hash"`
	Attempts    int32      `json:"attempts"`
	MaxAttempts int32      `json:"max_attempts"`
	ExpiresAt   time.Time  `json:"expires_at"`
	ConsumedAt  *time.Time `json:"consumed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type IdempotencyRecord struct {
	ID               uuid.UUID  `json:"id"`
	UserID           *uuid.UUID `json:"user_id"`
	IdempotencyKey   string     `json:"idempotency_key"`
	Operation        string     `json:"operation"`
	RequestHash      string     `json:"request_hash"`
	ResponseStatus   int32      `json:"response_status"`
	ResponseBodyJson []byte     `json:"response_body_json"`
	CreatedAt        time.Time  `json:"created_at"`
	ExpiresAt        time.Time  `json:"expires_at"`
}

type Friendship struct {
	ID              uuid.UUID  `json:"id"`
	RequesterID     uuid.UUID  `json:"requester_id"`
	AddresseeID     uuid.UUID  `json:"addressee_id"`
	UserLowID       uuid.UUID  `json:"user_low_id"`
	UserHighID      uuid.UUID  `json:"user_high_id"`
	Status          string     `json:"status"`
	RequestedAt     time.Time  `json:"requested_at"`
	AcceptedAt      *time.Time `json:"accepted_at"`
	RemovedAt       *time.Time `json:"removed_at"`
	BlockedByUserID *uuid.UUID `json:"blocked_by_user_id"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type Loan struct {
	ID                  uuid.UUID  `json:"id"`
	ReferenceCode       string     `json:"reference_code"`
	BorrowerID          uuid.UUID  `json:"borrower_id"`
	LenderID            uuid.UUID  `json:"lender_id"`
	InitiatorID         uuid.UUID  `json:"initiator_id"`
	Status              string     `json:"status"`
	PrincipalAmount     *string    `json:"principal_amount"`
	CurrencyCode        *string    `json:"currency_code"`
	InterestRatePercent *string    `json:"interest_rate_percent"`
	InterestAmount      *string    `json:"interest_amount"`
	ExpectedTotal       *string    `json:"expected_total"`
	OutstandingAmount   *string    `json:"outstanding_amount"`
	DueAt               *time.Time `json:"due_at"`
	Note                *string    `json:"note"`
	CurrentTermsID      *uuid.UUID `json:"current_terms_id"`
	AcceptedTermsID     *uuid.UUID `json:"accepted_terms_id"`
	TermsVersion        *int32     `json:"terms_version"`
	ProposedByUserID    *uuid.UUID `json:"proposed_by_user_id"`
	AcceptedAt          *time.Time `json:"accepted_at"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

type LoanTerm struct {
	ID                  uuid.UUID `json:"id"`
	LoanID              uuid.UUID `json:"loan_id"`
	Version             int32     `json:"version"`
	PrincipalAmount     string    `json:"principal_amount"`
	CurrencyCode        string    `json:"currency_code"`
	InterestRatePercent string    `json:"interest_rate_percent"`
	InterestAmount      string    `json:"interest_amount"`
	ExpectedTotal       string    `json:"expected_total"`
	DueAt               time.Time `json:"due_at"`
	Note                *string   `json:"note"`
	ProposedByUserID    uuid.UUID `json:"proposed_by_user_id"`
	Status              string    `json:"status"`
	CreatedAt           time.Time `json:"created_at"`
}

type LoanEvent struct {
	ID        uuid.UUID  `json:"id"`
	LoanID    uuid.UUID  `json:"loan_id"`
	ActorID   *uuid.UUID `json:"actor_id"`
	EventType string     `json:"event_type"`
	Payload   []byte     `json:"payload"`
	CreatedAt time.Time  `json:"created_at"`
}

type BankProfile struct {
	ID                         uuid.UUID  `json:"id"`
	UserID                     uuid.UUID  `json:"user_id"`
	ProfileType                string     `json:"profile_type"`
	Label                      string     `json:"label"`
	InstitutionName            *string    `json:"institution_name"`
	AccountIdentifierEncrypted []byte     `json:"account_identifier_encrypted"`
	AccountLast4               string     `json:"account_last4"`
	CurrencyCode               *string    `json:"currency_code"`
	IsPreferred                bool       `json:"is_preferred"`
	ArchivedAt                 *time.Time `json:"archived_at"`
	CreatedAt                  time.Time  `json:"created_at"`
	UpdatedAt                  time.Time  `json:"updated_at"`
}

type BankProfileShare struct {
	ID            uuid.UUID  `json:"id"`
	BankProfileID uuid.UUID  `json:"bank_profile_id"`
	OwnerID       uuid.UUID  `json:"owner_id"`
	RecipientID   uuid.UUID  `json:"recipient_id"`
	LoanID        *uuid.UUID `json:"loan_id"`
	CreatedAt     time.Time  `json:"created_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
}

type BankProfileEvent struct {
	ID            uuid.UUID  `json:"id"`
	BankProfileID uuid.UUID  `json:"bank_profile_id"`
	ShareID       *uuid.UUID `json:"share_id"`
	ActorID       *uuid.UUID `json:"actor_id"`
	EventType     string     `json:"event_type"`
	Payload       []byte     `json:"payload"`
	CreatedAt     time.Time  `json:"created_at"`
}

type Repayment struct {
	ID                 uuid.UUID  `json:"id"`
	LoanID             uuid.UUID  `json:"loan_id"`
	SubmittedByUserID  uuid.UUID  `json:"submitted_by_user_id"`
	Amount             string     `json:"amount"`
	Status             string     `json:"status"`
	Note               *string    `json:"note"`
	ProofAttachmentID  *uuid.UUID `json:"proof_attachment_id"`
	SubmittedAt        time.Time  `json:"submitted_at"`
	ConfirmedByUserID  *uuid.UUID `json:"confirmed_by_user_id"`
	ConfirmedAt        *time.Time `json:"confirmed_at"`
	RejectedAt         *time.Time `json:"rejected_at"`
	RejectionReason    *string    `json:"rejection_reason"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
}
