// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID                  uuid.UUID  `json:"id"`
	Email               string     `json:"email"`
	PhoneE164           *string    `json:"phone_e164"`
	Username            *string    `json:"username"`
	DisplayName         string     `json:"display_name"`
	AvatarObjectKey     *string    `json:"avatar_object_key"`
	Timezone            string     `json:"timezone"`
	Locale              string     `json:"locale"`
	DefaultCurrencyCode *string    `json:"default_currency_code"`
	PasswordHash        string     `json:"password_hash"`
	EmailVerifiedAt     *time.Time `json:"email_verified_at"`
	Status              string     `json:"status"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           *time.Time `json:"deleted_at"`
}

type UserSession struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	DeviceLabel      *string    `json:"device_label"`
	CreatedAt        time.Time  `json:"created_at"`
	LastUsedAt       time.Time  `json:"last_used_at"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
}

type VerificationChallenge struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Channel     string     `json:"channel"`
	Destination string     `json:"destination"`
	CodeHash    string     `json:"code_hash"`
	Attempts    int32      `json:"attempts"`
	MaxAttempts int32      `json:"max_attempts"`
	ExpiresAt   time.Time  `json:"expires_at"`
	ConsumedAt  *time.Time `json:"consumed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type IdempotencyRecord struct {
	ID               uuid.UUID  `json:"id"`
	UserID           *uuid.UUID `json:"user_id"`
	IdempotencyKey   string     `json:"idempotency_key"`
	Operation        string     `json:"operation"`
	RequestHash      string     `json:"request_hash"`
	ResponseStatus   int32      `json:"response_status"`
	ResponseBodyJson []byte     `json:"response_body_json"`
	CreatedAt        time.Time  `json:"created_at"`
	ExpiresAt        time.Time  `json:"expires_at"`
}
