// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  display_name,
  timezone,
  locale
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, phone_e164, username, display_name, avatar_object_key, timezone, locale, default_currency_code, password_hash, email_verified_at, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Timezone     string `json:"timezone"`
	Locale       string `json:"locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Timezone,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneE164,
		&i.Username,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.Timezone,
		&i.Locale,
		&i.DefaultCurrencyCode,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone_e164, username, display_name, avatar_object_key, timezone, locale, default_currency_code, password_hash, email_verified_at, status, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneE164,
		&i.Username,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.Timezone,
		&i.Locale,
		&i.DefaultCurrencyCode,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone_e164, username, display_name, avatar_object_key, timezone, locale, default_currency_code, password_hash, email_verified_at, status, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneE164,
		&i.Username,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.Timezone,
		&i.Locale,
		&i.DefaultCurrencyCode,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users
SET email_verified_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, phone_e164, username, display_name, avatar_object_key, timezone, locale, default_currency_code, password_hash, email_verified_at, status, created_at, updated_at, deleted_at
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneE164,
		&i.Username,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.Timezone,
		&i.Locale,
		&i.DefaultCurrencyCode,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  display_name = COALESCE($1, display_name),
  timezone = COALESCE($2, timezone),
  locale = COALESCE($3, locale),
  default_currency_code = COALESCE($4, default_currency_code),
  updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, email, phone_e164, username, display_name, avatar_object_key, timezone, locale, default_currency_code, password_hash, email_verified_at, status, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	DisplayName         *string   `json:"display_name"`
	Timezone            *string   `json:"timezone"`
	Locale              *string   `json:"locale"`
	DefaultCurrencyCode *string   `json:"default_currency_code"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Timezone,
		arg.Locale,
		arg.DefaultCurrencyCode,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneE164,
		&i.Username,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.Timezone,
		&i.Locale,
		&i.DefaultCurrencyCode,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
  user_id,
  refresh_token_hash,
  device_label,
  expires_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, refresh_token_hash, device_label, created_at, last_used_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID `json:"user_id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	DeviceLabel      *string   `json:"device_label"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceLabel,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, device_label, created_at, last_used_at, expires_at, revoked_at FROM user_sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, device_label, created_at, last_used_at, expires_at, revoked_at FROM user_sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_sessions
SET last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const rotateSession = `-- name: RotateSession :one
UPDATE user_sessions
SET refresh_token_hash = $2,
    last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, device_label, created_at, last_used_at, expires_at, revoked_at
`

type RotateSessionParams struct {
	ID               uuid.UUID `json:"id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.RefreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceLabel,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const invalidateOpenChallenges = `-- name: InvalidateOpenChallenges :exec
UPDATE verification_challenges
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidateOpenChallenges(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateOpenChallenges, userID)
	return err
}

const createVerificationChallenge = `-- name: CreateVerificationChallenge :one
INSERT INTO verification_challenges (
  user_id,
  channel,
  destination,
  code_hash,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, channel, destination, code_hash, attempts, max_attempts, expires_at, consumed_at, created_at
`

type CreateVerificationChallengeParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Channel     string    `json:"channel"`
	Destination string    `json:"destination"`
	CodeHash    string    `json:"code_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, createVerificationChallenge,
		arg.UserID,
		arg.Channel,
		arg.Destination,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestOpenChallenge = `-- name: GetLatestOpenChallenge :one
SELECT id, user_id, channel, destination, code_hash, attempts, max_attempts, expires_at, consumed_at, created_at FROM verification_challenges
WHERE user_id = $1 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOpenChallenge(ctx context.Context, userID uuid.UUID) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getLatestOpenChallenge, userID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementChallengeAttempts = `-- name: IncrementChallengeAttempts :one
UPDATE verification_challenges
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, user_id, channel, destination, code_hash, attempts, max_attempts, expires_at, consumed_at, created_at
`

func (q *Queries) IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, incrementChallengeAttempts, id)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeChallenge = `-- name: ConsumeChallenge :exec
UPDATE verification_challenges
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeChallenge, id)
	return err
}
