// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumeChallenge(ctx context.Context, id uuid.UUID) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenge, error)
	GetLatestOpenChallenge(ctx context.Context, userID uuid.UUID) (VerificationChallenge, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) (VerificationChallenge, error)
	InvalidateOpenChallenges(ctx context.Context, userID uuid.UUID) error
	MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error)
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RotateSession(ctx context.Context, arg RotateSessionParams) (UserSession, error)
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	InsertFriendship(ctx context.Context, arg InsertFriendshipParams) (Friendship, error)
	GetFriendshipByID(ctx context.Context, id uuid.UUID) (Friendship, error)
	GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error)
	UpdateFriendship(ctx context.Context, arg UpdateFriendshipParams) (Friendship, error)
	ListAcceptedFriendships(ctx context.Context, userID uuid.UUID) ([]Friendship, error)
	ListIncomingFriendRequests(ctx context.Context, addresseeID uuid.UUID) ([]Friendship, error)
	ListOutgoingFriendRequests(ctx context.Context, requesterID uuid.UUID) ([]Friendship, error)
}

var _ Querier = (*Queries)(nil)
