// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type OpenLoanForReconcile struct {
	ID                uuid.UUID `json:"id"`
	ReferenceCode     string    `json:"reference_code"`
	Status            string    `json:"status"`
	ExpectedTotal     *string   `json:"expected_total"`
	OutstandingAmount *string   `json:"outstanding_amount"`
}

const listOpenLoansForReconcile = `-- name: ListOpenLoansForReconcile :many
SELECT id, reference_code, status, expected_total, outstanding_amount
FROM loans
WHERE status IN ('active', 'overdue', 'repayment_pending')
`

func (q *Queries) ListOpenLoansForReconcile(ctx context.Context) ([]OpenLoanForReconcile, error) {
	rows, err := q.db.Query(ctx, listOpenLoansForReconcile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenLoanForReconcile{}
	for rows.Next() {
		var i OpenLoanForReconcile
		if err := rows.Scan(&i.ID, &i.ReferenceCode, &i.Status, &i.ExpectedTotal, &i.OutstandingAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const sumConfirmedRepayments = `-- name: SumConfirmedRepayments :one
SELECT COALESCE(SUM(amount), 0)::text AS total
FROM repayments
WHERE loan_id = $1 AND status = 'confirmed'
`

func (q *Queries) SumConfirmedRepayments(ctx context.Context, loanID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, sumConfirmedRepayments, loanID)
	var total string
	err := row.Scan(&total)
	return total, err
}
